
FROM golang:1.23-alpine AS builder
RUN apk add --no-cache git gcc musl-dev sqlite
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=1 GOOS=linux go build -a -ldflags '-extldflags "-static"' -o distributed-app ./cmd/distributed-app

FROM alpine:latest
RUN apk add --no-cache ca-certificates sqlite
WORKDIR /app
COPY --from=builder /app/distributed-app .
RUN mkdir -p /app/space184
EXPOSE 6996 9000-9010
CMD ["./distributed-app"]
